% Amend MATLAB PATH to handle MRST implementation.

% $Date: 2009-10-01 16:39:10 +0200 (to, 01 okt 2009) $
% $Revision: 2927 $

cd utils
p = strcat(ROOTDIR,                                   ...
           {                                          ...
            '',                                       ...
            'doc',                                    ...
            'examples',                               ...
           ['examples', filesep, '1ph'],              ...
           ['examples', filesep, '2ph'],              ...
           ['examples', filesep, 'grids'],            ...
            'gridprocessing',                         ...
           ['gridprocessing', filesep, 'testgrids'],  ...
            'params',                                 ...
           ['params', filesep, 'fluid'],              ...
           ['params', filesep, 'fluid', filesep, 'compressible'], ...
           ['params', filesep, 'fluid', filesep, 'incompressible'], ...
           ['params', filesep, 'fluid', filesep, 'utils'], ...
           ['params', filesep, 'rock'],               ...
           ['params', filesep, 'wells_and_bc'],       ...
            'plotting',                               ...
            'regression',                             ...
           ['regression', filesep, 'tests'],          ...
            'solvers',                                ...
           ['solvers', filesep, 'adjoint'],           ...
           ['solvers', filesep, 'adjoint', filesep, 'objectives'], ...
           ['solvers', filesep, 'adjoint', filesep, 'tests'],      ...
           ['solvers', filesep, 'adjoint', filesep, 'enkf'],       ...
           ['solvers', filesep, 'mimetic'],           ...
           ['solvers', filesep, 'mimetic', filesep, 'utils'], ...
           ['solvers', filesep, 'msmfem'],            ...
           ['solvers', filesep, 'msmfem', filesep, 'utils'], ...
           ['solvers', filesep, 'nuc'],               ...
           ['solvers', filesep, 'stokes-brinkman'],   ...
           ['solvers', filesep, 'stokes-brinkman', filesep, 'plotting'],   ...
           ['solvers', filesep, 'tpfa'],              ...
           ['solvers', filesep, 'transport'],         ...
           ['solvers', filesep, 'upscaling'],         ...
            'tests',                                  ...
            'utils',                                  ...
           ['utils', filesep, 'units'],               ...
           ['utils', filesep, 'inout'],               ...
            'iterative_ms',                           ... % Integrate into package
            'lbfgs',                                  ...
           }, pathsep);
addpath([p{:}]);
clear p;
cd ..
