function writeSummary(header, table, rowcolor, filename)
%
%
%
%
%

fs = fopen(filename, 'w');


writeBegin(fs)
writeTableHTML(fs, header, table, rowcolor)
writeEnd(fs);


fclose(fs);



function writeTableHTML(fs, header, table, rowcolor)
%
% Write column headers
fprintf(fs, '<html><table CELLPADDING=\"10%%\" WIDTH=\"800\" COLS=\"4\"  ><tr bgcolor=#00CCFF>\n');
for i = 1:size(table, 2), fprintf(fs,  '<th>%s</th>', header{i}); end
fprintf(fs, '</tr>\n');


% Write table
for i = 1:size(table, 1)
    fprintf(fs, '<tr bgcolor="%s">\n', rowcolor{i});

    for j = 1:size(table, 2)
        switch class(table{i,j})
            case 'double'
                fprintf(fs,  '<td>%f</td>', table{i,j});

            case 'char'
                fprintf(fs,  '<td>%s</td>', table{i,j});
        end
    end
    fprintf(fs, '</tr>\n');
end
fprintf(fs, '</table></html>\n');



function writeBegin(fp)
fprintf(fp,'%s', ...
['<!DOCTYPE html  PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN">' ...
'<html xmlns:mwsh="http://www.mathworks.com/namespace/mcode/v1/syntaxhighlight.dtd">' ...
'  <head>' ...
'    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">' ...
'' ...
'    <title>Nightly Tests</title>' ...
'    <meta name="generator" content="MATLAB 7.6">' ...
'    <meta name="date" content="2008-12-04">' ...
'    <meta name="m-file" content="report">' ...
'' ...
'    <style>' ...
'' ...
'      body {' ...
'      background-color: white;' ...
'      margin:10px;' ...
'      }' ...
'' ...
'      h1 {' ...
'      color: #990000;' ...
'      font-size: x-large;' ...
'      }' ...
'' ...
'      h2 {' ...
'      color: #990000;' ...
'      font-size: medium;' ...
'      }' ...
'' ...
'      /* Make the text shrink to fit narrow windows, but not stretch too far in' ...
'      wide windows. */' ...
'      p,h1,h2,div.content div {' ...
'      max-width: 600px;' ...
'      /* Hack for IE6 */' ...
'      width: auto !important; width: 600px;' ...
'      }' ...
'' ...
'' ...
'      p.footer {' ...
'      text-align: right;' ...
'      font-size: xx-small;' ...
'      font-weight: lighter;' ...
'      font-style: italic;' ...
'      color: gray;' ...
'      }' ...
'' ...
'    </style>' ...
'  </head>' ...
'' ...
'  <body>' ...
'    <div class="content">' ...
'      <h1>Summary of test results</h1>' ...
'      <introduction>' ...
'        <p>']);

function writeEnd(fp)
fprintf(fp, '%s', ...
['      </p>' ...
'      </introduction>' ...
'      <p class="footer"><br>' ...
'       Published with MATLAB&reg; 7.6<br></p>' ...
'    </div>' ...
'' ...
'  </body>' ...
'</html>']);




