disp('Building trilinosmex...');
mex -largeArrayDims -cxx  -o trilinosmex  -lml -lamesos -lifpack -laztecoo ...
    -lepetra -lepetraext -lteuchos -lumfpack -lamd -lmwlapack -lmwblas      ...
    trilinosmex.cpp trilinos.cpp -I/usr/local/include/trilinos/   
  
